name: azure-deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      env_file:
        required: true
        type: string
      bicepTemplateFile:
        required: true
        type: string
      bicepParameterFile:
        required: true
        type: string

jobs:
  azure-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: "Remove Quotation Marks from Environment File"
      #  uses: azure/powershell@v1
      #  with:
      #    inlineScript: |
      #      Write-Host ${{ inputs.env_file }}
      #      (Get-Content -Path ${{ inputs.env_file }} -Encoding UTF8) | ForEach-Object {$_ -replace '"',''} | Out-File -FilePath ${{ inputs.env_file }} -Encoding UTF8
      #    azPSVersion: "latest"

      #- name: Import Environment Variables from File
      #  run: cat ${{ inputs.env_file }} >> $GITHUB_ENV

      - name: OIDC Login to Tenant
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Azure Workload Deployment"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-AzureWorkload.ps1 -TemplateFile ${{ inputs.bicepTemplateFile }} -TemplateParameterFile ${{ inputs.bicepParameterFile }} -Verbose
          azPSVersion: "11.0.0"
