name: azure-deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      env_file:
        required: true
        type: string
      artifact_name:
        default: artifact
        required: false
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
jobs:
  azure-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Remove Quotation Marks from Environment File"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Write-Host ${{ inputs.env_file }}
            (Get-Content -Path ${{ inputs.env_file }} -Encoding UTF8) | ForEach-Object {$_ -replace '"',''} | Out-File -FilePath ${{ inputs.env_file }} -Encoding UTF8
          azPSVersion: "latest"

      - name: Import Environment Variables from File
        run: cat ${{ inputs.env_file }} >> $GITHUB_ENV

      - name: OIDC Login to Tenant
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Azure Workload Deployment"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-AzureWorkload.ps1 -Verbose
          azPSVersion: "11.0.0" # required to deploy bicepparam. Change to latest when ubuntu-latest ships by default with azure pwsh >=11

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_name }}

      # Publish function app
      - name: "Publish function app"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pipeline-scripts\Publish-IcrProject.ps1 -ARCHIVE_PATH ${{ inputs.artifact_name}}/output.zip -Verbose
          azPSVersion: "11.0.0"
