name: deploy-reporting

on:
  push:
    branches:
      - main
    #paths:
    #  - 'infra-as-code/reporting/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  reporting-dev:
    uses: ./.github/workflows/reusable/azure-deploy-reusable.yml
    with:
      env_file: ".d.env"
      bicepTemplateFile: infra-as-code/reporting/main.bicep
      bicepParameterFile: infra-as-code/reporting/main.d.bicepparam

  reporting-prod:
    uses: ./.github/workflows/reusable/azure-deploy-reusable.yml
    needs: reporting-dev
    with:
      env_file: ".p.env"
      bicepTemplateFile: infra-as-code/reporting/main.bicep
      bicepParameterFile: infra-as-code/reporting/main.p.bicepparam
